### PR TITLE
Feat/jsonpath

### PR DESCRIPTION
**Pull request by damienklinnert**
I discovered hjsonschema when looking for a json schema validation library for my Haskell projects. It looks really promising, but is missing one important feature for me: A description of where exactly in the data the error occurred.

I'm still a Haskell beginner, but tried to add this feature anyway. I'd appreciate detailed feedback to get this pull request into a mergeable state. It appears to be working as-is, but is far from perfect. It might also require some refactoring / clean up.

Thanks for building this awesome library so far!

### CODE REVIEW

**Comment by seagreen** [comment]
Interesting. Including the path to the failing data is a good addition to `FailureInfo`. This will also be a good thing to have around when I get to fixing this issue: https://github.com/seagreen/hjsonschema/issues/29 because we'll need to be able to know when a schema is used against the same piece of data twice in one validation run, and knowing the path to each piece of data will be a great thing to have then.

As nice as this is, merging it is going to take a little bit of thinking. I currently have a big branch forked off to try to implement this: https://github.com/seagreen/hjsonschema/issues/28. Honestly it's closer to a rewrite than a normal commit as almost every internal type signature is going to change. I think when that's done (hopefully in a few days) we can decide whether to merge this and then rebase my changes over it, or to push up my changes and then implement path tracking on top of them.

How does that sound? Sorry to suggest waiting on this PR, but the changes are pretty big and I'd rather get path tracking perfect once than merge it now and then have to make changes to it so soon.

**Comment by damienklinnert** [comment]
Great to hear your actively maintaining this project. I'm perfectly fine with waiting a couple of days. Would love to have path tracking soon though :) Keep me posted once you've made a decision and let me know how I can help you.

**Comment by seagreen** [comment]
Down to one failing test on the new branch: https://github.com/seagreen/hjsonschema/tree/wip (those won't be canonical commits -- they'll all be squashed down soon but it shows what I'm up to).

Once that's done adding the new error info will be my next priority.

**Comment by damienklinnert** [comment]
Thanks for the update! Super eager to add this library to my project! Anyway I can help you?

**Comment by seagreen** [comment]
Holy smoke, finally got the rewrite in close to working order: https://github.com/seagreen/hjsonschema/tree/wip

We can now write our schemas in haskell. This is better than the old way where schemas had to be json. You can still start with json and then parse it to a haskell `Schema` yourself or you can write a `Schema` directly now. An example is here: https://github.com/seagreen/hjsonschema/blob/wip/Example.hs#L27

Next step: take a look at the new code and see if it's understandable. If it is and you'd like to add jsonpath info to failures let me know. In that case I'll make a `0.9` branch for us both to work off of (in the meantime I may be rebasing over the `wip` branch, so don't actually code off of that).

If you'd rather I change the PR to work with the new hjsonschema code instead I'll be happy to, just let me know.

**Comment by seagreen** [comment]
By the way, what's your use case for having the json path to the failing data? Are you going to be displaying that info to a human, or is it going to be used as the input for other functions?

**Comment by damienklinnert** [comment]
Thanks for the update - I can try to add jsonpath back in - is a good exercise and I'm happy to help. Let's do the 0.9 branch - just let me know once it's ready and I can code against it.

I'm building a webservice api and want to
a) specify valid inputs via json schema
b) respond with a meaningful error message in case of failure

**Comment by seagreen** [comment]
0.9 branch pushed up: https://github.com/seagreen/hjsonschema/tree/0.9

**Comment by seagreen** [comment]
I'd like to add your new JSON pointer data type to the hjsonpointer library: https://github.com/seagreen/hjsonpointer, it can be exported by hjsonschema as well so that people don't have to add hjsonpointer to their cabal files.

I'm thinking maybe it should be called `JsonPointer` though instead of `JsonPath`, because that's how it's referred to in the RFC: http://tools.ietf.org/html/rfc6901. It looks like there's also a thing called JSONPath, but it works a little differently: http://goessner.net/articles/JsonPath/index.html#e2

**Comment by seagreen** [comment]
Started on adding a JSON Pointer data type to hjsonpointer instead of just using a newtype for [Text].

**Comment by seagreen** [comment]
Alright, things are set up to get paths to failing data working.

### Compiling

Check out the 0.9 branch of hjsonschema.

Clone `https://github.com/seagreen/hjsonpointer` and checkout the 0.3 branch. Add this as a local dependency of your cabal sandbox. This version of hjsonpointer it provides is actually 0.2.0.6 -- this is ahead of hackage, but I haven't bumped it up to 0.3 yet because we might need to make more changes. Cabal stays happier if each change of the code is reflected by a change of the version, and if version numbers never go backwards.

That's it!

### Coding

Two things you can help with:

1) Look over what I've done so far and let me know what you think.

The JSON Pointer data type is declared here: https://github.com/seagreen/hjsonpointer/blob/0.3/src/Data/JsonPointer.hs#L17. I called it `JsonPointer` instead of `JSONPointer`, perhaps I should have copied aeson and used caps for JSON, but capitalized abbreviations look questionable to me at the start of camelcase names. Feel free to help me bikeshed this, my conscience tells me I should consider using caps like you did . . . argh!

I also called the two types of pointer tokens `IntegerToken` and `TextToken` instead of your more descriptive `Index` and `Key`. This I'm more sure about since an `Index` isn't actually just an index -- it can also be a key depending on what it's used against. Because of this I actually wanted to use _less_ descriptive words here to try to help avoid implying the wrong thing to users of the lib.

Also feel free to generally look over the changes if you want and make suggestions.

2) This is the big one: right now all the JSON Pointers returned by the validators are just dud values -- they're all set to `mempty`. If you want to go through the `0.9` branch and fix that it would be awesome. I know this has take a long time for me to get ready though, so if your schedule has changed or for whatever reason it isn't convenient for you right now let me know and I'll take a shot at it.

Thanks for your help on this:) :rainbow:

**Comment by seagreen** [comment]
I've got time to take care of this in the next couple days. Let me know if you've already started on it, otherwise I'll try to knock it out.

**Comment by seagreen** [comment]
Finally took care of this.

Here's an example of how the internals work, based on your original PR: https://github.com/seagreen/hjsonschema/blob/master/src/Data/Validator/Draft4/Array.hs#L79

Here's the failure data type: https://github.com/seagreen/hjsonschema/blob/master/src/Data/Validator/Failure.hs#L26

There's a version of that data type specialized for draft 4 here: https://github.com/seagreen/hjsonschema/blob/master/src/Data/JsonSchema/Draft4/Failure.hs#L10 This is what the functions in `Data.JsonSchema.Draft4` (the primary entry point to the library) return.

Now that our failure type returns pointers to failing data, we no longer need to return the subset of the data that caused the failure (since it can be derived from the original data and the pointer). An example of how to do that derivation is here: https://github.com/seagreen/hjsonschema/blob/master/examples/PrettyShowFailure.hs#L21

Thanks for all your help on this. In addition to basing my code on yours, your original idea of including the JSON Pointer to the bad subset of the data was clearly a good one.

**Pull request closed without merging**
